### ISSUE TITLE
Detailed steps ?

### ISSUE THREAD

**Issue by anujgupta82** [jupyterhub/jupyterhub-example-kerberos#2]
is there a detailed step-by-step instructions that one can follow to install and run this ?

**Comment by willingc** [comment]
Hi @anujgupta82,

Thanks for your interest in this. This particular repo is a place where people can experiment with JupyterHub and Kerberos. As the README states, it is not meant for production:

> This project exists to help you (and us) learn how JupyterHub and Kerberos can interoperate. It will never provide an out-of-the-box, production-ready experience.

> At the moment, it is very much a work in progress. If you have experience configuring JupyterHub with Kerberos, please jump in and help us out!

If you would like, you could leave a message on the Jupyter Google group asking others if they have a detailed step-by-step in one of their own deployments with Kerberos. Thanks!
