### ISSUE TITLE
hub docker image installs unversioned dependencies

### ISSUE THREAD

**Issue by harschware** [jupyterhub/jupyterhub-example-kerberos#4]
suggestion:   with the 5.1.0 release of notebook recently, and hub 0.8.0 coming out.  I think you want to pin the versions of those and other dependencies in your docker files to ensure they are tested versions.

**Comment by minrk** [comment]
An excellent idea. Would you like to make a PR?

**Comment by harschware** [comment]
I would :-)   Just learned about this project last night.  Hoping to learn a thing or two about kerberos in jupyterhub from it.

**Comment by parente** [comment]
I think this was closed by #5 . Thanks for that @harschware. 🍰
